# Generated by Django 4.1.2 on 2025-04-04 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("solar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.AlterField(
            model_name="installationrequest",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="installationrequest",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "technician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technician_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="custom_user_groups",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_permissions",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterModelTable(name="user", table="auth_user",),
    ]
