# Generated by Django 4.1.2 on 2025-04-06 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0003_installationrequest_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installationrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
